---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При переключении языка страницы сайт должен отображается на выбранный язык
  - При просмотре списка товаров, у пользователя должна быть возможность выбрать вид списка для удобства пользования
  - При добавлении товара в корзину, должно происходить действие подтвержадющее добавление товара для удобства пользователя
  - Во вкладке "корзина" перед оформлением заказа, должна быть возможность изменить количество товара
  - Во вкладке "корзина" таблица просмотра выбранных товаров, должна быть понятной пользователю, необходимо добавить наименовани позиций
  - Пользователь должен иметь возможность сохранить выбранные товары при следующем посещении сайта
  - Должна быть форма регистрации для сохранения данных пользователя
  - При просмотре/выборе товара, у пользователя должна быть возможность открыть фотографию из списка описаний для удобства просмотра
  - Перед добавлением товара в корзину, у пользователя должна быть возможность выбрать нужное количество
